In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [14]:
def power(x,y):
    return x ** y

In [16]:
power(2,7)

128

In [18]:
@tf.function
def tf_power(x,y):
    return x ** y

In [19]:
tf_power(2,7)

<tf.Tensor: shape=(), dtype=int32, numpy=128>

In [20]:
tf_power(8,6)

<tf.Tensor: shape=(), dtype=int32, numpy=262144>

In [8]:
@tf.function
def make_tensor(x):
    return x

In [9]:
make_tensor(100)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [10]:
make_tensor('a')

<tf.Tensor: shape=(), dtype=string, numpy=b'a'>

In [11]:
make_tensor([1,2,3,4,5,6,7])

[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>]

In [12]:
import numpy as np

In [13]:
make_tensor(np.array([1,2,3,4,5,6,7]))

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7])>